services:
  # Frontend build and serve (Bun + node)
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env.production
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongo
    networks:
      - sonex-network
  # Database (MongoDB)
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    env_file:
      - ./server/.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - sonex_data:/data/db
    networks:
      - sonex-network
    healthcheck:
      test: ["CMD", "mongo", "--version"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  sonex-network:
    driver: bridge
volumes:
  sonex_data:
    driver: local
