services:
  # Frontend build and serve (Bun + node)
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env.production
    environment:
      - NODE_ENV=production
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgres
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    networks:
      - sonex-network
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - ./server/.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - sonex_data:/var/lib/postgresql/data
    networks:
      - sonex-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  sonex-network:
    driver: bridge
volumes:
  sonex_data:
    driver: local
